# Generated by Django 3.1 on 2020-09-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='numerosprimos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('primo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='primosgemelos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('gemelos', models.CharField(max_length=20)),
            ],
        ),
    ]
