# Generated by Django 3.1 on 2020-09-03 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Punto4', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='numerosprimos',
            new_name='tabla_numerosprimos',
        ),
        migrations.RenameModel(
            old_name='primosgemelos',
            new_name='tabla_primosgemelos',
        ),
    ]
